version: '3.1'

services:
  postgres:
    image: postgres:15
    container_name: postgres-cardealership
    restart: unless-stopped # <- mantém o container rodando após reinicialização do sistema
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cardealership
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: pgdata_cardealership